AllCops:
  DisplayCopNames: true
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**/*
    - test/**/*
    - spec/**/*

# TODO: Whittle down the exceptions over time
RescueStandardError:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
BlockLength:
  Enabled: false
NumericLiteralPrefix:
  Enabled: false
AbcSize:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Max: 7
HeredocDelimiterNaming:
  Enabled: false
