language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_YAML=.kitchen.travis.yml
    - OMNIBUS_CHEF_VERSION=13

rvm:
  - 2.5.0

sudo: required
dist: trusty

before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis
  - echo "rubygems 2.7.5 - https://github.com/berkshelf/berkshelf/issues/1744"
  - gem update --system 2.7.5

script:
  - bundle install
  - bundle exec rake style
  - bundle exec rake unit

branches:
  only:
  - master
